name: "Commit Message and PR Check"
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  push:
    branches:
      - master
      - "releases/*"

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^(feat|fix|chore|docs|style|refactor|perf|test):? .+|^build\(deps(-dev)?\): .+|^Merge branch.+$'
          flags: "gm"
          error: 'Your first line has to follow the format: prefix(#GitHub Issue Number): description or the dependabot format like "build(deps): ...". For example: feat(#12): Add new filter functionality. The #GitHub Issue Number is optional.'
